// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFBAQKvk7HQPrI73ZvclmC5m4f2Vqdnts',
    appId: '1:594417147820:web:cbad0e7f1cd61306fb2409',
    messagingSenderId: '594417147820',
    projectId: 'weavin-9311b',
    authDomain: 'weavin-9311b.firebaseapp.com',
    storageBucket: 'weavin-9311b.appspot.com',
    measurementId: 'G-V1CFB2ZJMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvTi4rKilhQhRpmRUWJa8u6ojvyqUSa7Q',
    appId: '1:594417147820:android:9b16a72d0fb281a8fb2409',
    messagingSenderId: '594417147820',
    projectId: 'weavin-9311b',
    storageBucket: 'weavin-9311b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-QhHUc1fIV-047gzsiqq7u32XlY97O5w',
    appId: '1:594417147820:ios:bc098447c662541ffb2409',
    messagingSenderId: '594417147820',
    projectId: 'weavin-9311b',
    storageBucket: 'weavin-9311b.appspot.com',
    iosBundleId: 'com.example.firebaseSignin',
  );
}
